/*
 * Generated by JasperReports - 2007-01-08 16:16
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class JasperDocument_1168269391484_796027 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_voucherrow46credet = null;
    private JRFillField field_voucherrow46project = null;
    private JRFillField field_voucherrow46isadded = null;
    private JRFillField field_voucherrow46account = null;
    private JRFillField field_voucherrow46resultunit = null;
    private JRFillField field_voucherrow46ismarked = null;
    private JRFillField field_voucherrow46iscrossed = null;
    private JRFillField field_voucherrow46debet = null;
    private JRFillField field_voucherrow46description = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_debet46sum = null;
    private JRFillVariable variable_credet46sum = null;
    private JRFillVariable variable_marked_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_voucherrow46credet = (JRFillField)fm.get("voucherrow.credet");
        field_voucherrow46project = (JRFillField)fm.get("voucherrow.project");
        field_voucherrow46isadded = (JRFillField)fm.get("voucherrow.isadded");
        field_voucherrow46account = (JRFillField)fm.get("voucherrow.account");
        field_voucherrow46resultunit = (JRFillField)fm.get("voucherrow.resultunit");
        field_voucherrow46ismarked = (JRFillField)fm.get("voucherrow.ismarked");
        field_voucherrow46iscrossed = (JRFillField)fm.get("voucherrow.iscrossed");
        field_voucherrow46debet = (JRFillField)fm.get("voucherrow.debet");
        field_voucherrow46description = (JRFillField)fm.get("voucherrow.description");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_debet46sum = (JRFillVariable)vm.get("debet.sum");
        variable_credet46sum = (JRFillVariable)vm.get("credet.sum");
        variable_marked_COUNT = (JRFillVariable)vm.get("marked_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.lang.Boolean)field_voucherrow46iscrossed.getValue()).booleanValue() ? new BigDecimal(0.0) : ((java.math.BigDecimal)field_voucherrow46debet.getValue()));
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.lang.Boolean)field_voucherrow46iscrossed.getValue()).booleanValue() ? new BigDecimal(0.0) : ((java.math.BigDecimal)field_voucherrow46credet.getValue()));
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.Boolean)field_voucherrow46ismarked.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46ismarked.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46iscrossed.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46isadded.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46account.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)field_voucherrow46description.getValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46project.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46resultunit.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_voucherrow46debet.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_voucherrow46credet.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_debet46sum.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_credet46sum.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.lang.Boolean)field_voucherrow46iscrossed.getOldValue()).booleanValue() ? new BigDecimal(0.0) : ((java.math.BigDecimal)field_voucherrow46debet.getOldValue()));
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.lang.Boolean)field_voucherrow46iscrossed.getOldValue()).booleanValue() ? new BigDecimal(0.0) : ((java.math.BigDecimal)field_voucherrow46credet.getOldValue()));
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.Boolean)field_voucherrow46ismarked.getOldValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46ismarked.getOldValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46iscrossed.getOldValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46isadded.getOldValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46account.getOldValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)field_voucherrow46description.getOldValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46project.getOldValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46resultunit.getOldValue()));
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_voucherrow46debet.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_voucherrow46credet.getOldValue()));
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_debet46sum.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_credet46sum.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.lang.Boolean)field_voucherrow46iscrossed.getValue()).booleanValue() ? new BigDecimal(0.0) : ((java.math.BigDecimal)field_voucherrow46debet.getValue()));
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.lang.Boolean)field_voucherrow46iscrossed.getValue()).booleanValue() ? new BigDecimal(0.0) : ((java.math.BigDecimal)field_voucherrow46credet.getValue()));
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Object)(((java.lang.Boolean)field_voucherrow46ismarked.getValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46ismarked.getValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46iscrossed.getValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Boolean)(((java.lang.Boolean)field_voucherrow46isadded.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46account.getValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.String)(((java.lang.String)field_voucherrow46description.getValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46project.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)field_voucherrow46resultunit.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_voucherrow46debet.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_voucherrow46credet.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_debet46sum.getEstimatedValue()));
                break;
            }
            case 25 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_credet46sum.getEstimatedValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
